# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
      - "infra/chart/**"


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
        env:
          HELM_CHART_PATH: 'infra/chart' # Update with the path to your Helm chart
          IMAGE_TAG: "test123"
      - run: |
          pwd
          ls -la
          sed -i "s|tag:.*|tag: $IMAGE_TAG|g" $HELM_CHART_PATH/values.yaml
          cat infra/chart/values.yaml
          git diff
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "New deployment: $IMAGE_TAG" -a
          git diff --stat origin/main
          git push origin main
        env:
          IMAGE_TAG: "test1234568"
          HELM_CHART_PATH: 'infra/chart'

    
